#!/bin/bash

# Setup Environment Variables Script
# Extracts values from CloudFormation stack outputs and creates .env file
# for the frontend (Vite) application.

set -e

# Resolve project root (parent of scripts/)
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

STACK_NAME=${1:-genai-campaign-agentcore}
AWS_REGION=${2:-${AWS_DEFAULT_REGION:-us-west-2}}
AGENT_RUNTIME_ID=${3:-}

echo "🔍 Getting environment variables from CloudFormation stack: $STACK_NAME"
echo "🌍 Region: $AWS_REGION"
echo ""

# Check if stack exists
if ! aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$AWS_REGION" >/dev/null 2>&1; then
    echo "❌ Stack '$STACK_NAME' not found in region $AWS_REGION"
    echo ""
    echo "Deploy first:"
    echo "  sam build && sam deploy --stack-name $STACK_NAME --region $AWS_REGION"
    echo ""
    echo "Or specify a different stack/region:"
    echo "  ./scripts/setup-env.sh <stack-name> <region>"
    exit 1
fi

echo "📊 Retrieving stack outputs..."

# Helper to pull a single output value
get_output() {
    aws cloudformation describe-stacks \
        --stack-name "$STACK_NAME" \
        --region "$AWS_REGION" \
        --query "Stacks[0].Outputs[?OutputKey==\`$1\`].OutputValue" \
        --output text 2>/dev/null
}

# --- VITE_S3_BUCKET (UnifiedBucket) ---
S3_BUCKET=$(get_output "UnifiedBucket")
if [ -z "$S3_BUCKET" ] || [ "$S3_BUCKET" = "None" ]; then
    echo "⚠️  Could not find UnifiedBucket output — using placeholder"
    S3_BUCKET="unified-campaign-review-test"
fi

# --- VITE_API_URL (HttpApi endpoint) ---
API_URL=$(get_output "ApiEndpoint")
if [ -z "$API_URL" ] || [ "$API_URL" = "None" ]; then
    echo "⚠️  Could not find ApiEndpoint output — using placeholder"
    API_URL="https://your-http-api-id.execute-api.$AWS_REGION.amazonaws.com"
fi

# --- VITE_AGENT_API_URL (REST API Gateway → review-campaign Lambda) ---
AGENT_API_URL=$(get_output "CampaignOrchestratorApi")
if [ -z "$AGENT_API_URL" ] || [ "$AGENT_API_URL" = "None" ]; then
    echo "⚠️  Could not find CampaignOrchestratorApi output — using placeholder"
    AGENT_API_URL="https://your-rest-api-id.execute-api.$AWS_REGION.amazonaws.com/Prod/review-campaign/"
fi

# --- AGENT_ARN_PARAM (SSM parameter for AgentCore Runtime ARN) ---
SSM_PARAM_NAME="/agentcore/campaign-review/agent-arn"

# If agent runtime ID was provided as 3rd argument, write it to SSM
if [ -n "$AGENT_RUNTIME_ID" ]; then
    ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text 2>/dev/null)
    AGENT_ARN="arn:aws:bedrock-agentcore:$AWS_REGION:$ACCOUNT_ID:runtime/$AGENT_RUNTIME_ID"
    echo "📝 Writing Agent ARN to SSM: $AGENT_ARN"
    aws ssm put-parameter \
        --name "$SSM_PARAM_NAME" \
        --value "$AGENT_ARN" \
        --type String \
        --overwrite \
        --region "$AWS_REGION" >/dev/null
    echo "   ✅ SSM parameter updated"
else
    echo "🔍 Checking SSM parameter: $SSM_PARAM_NAME"
    AGENT_ARN=$(aws ssm get-parameter \
        --name "$SSM_PARAM_NAME" \
        --region "$AWS_REGION" \
        --query "Parameter.Value" \
        --output text 2>/dev/null || true)

    if [ -z "$AGENT_ARN" ] || [ "$AGENT_ARN" = "None" ] || [ "$AGENT_ARN" = "PLACEHOLDER" ]; then
        echo "⚠️  Agent ARN not set in SSM (value: '${AGENT_ARN:-empty}')"
        echo "   Re-run with the agent runtime ID to set it:"
        echo "   ./scripts/setup-env.sh $STACK_NAME $AWS_REGION <agent-runtime-id>"
        echo ""
        AGENT_ARN="PLACEHOLDER"
    else
        echo "   ✅ Agent ARN: $AGENT_ARN"
    fi
fi

echo ""
echo "✅ Resolved values:"
echo "   VITE_S3_BUCKET:     $S3_BUCKET"
echo "   VITE_API_URL:       $API_URL"
echo "   VITE_AGENT_API_URL: $AGENT_API_URL"
echo "   Agent ARN (SSM):    $AGENT_ARN"
echo ""

# Write .env
echo "📝 Writing .env file..."

cat > "$PROJECT_ROOT/.env" << EOF
# Auto-generated by scripts/setup-env.sh on $(date)
# Stack: $STACK_NAME | Region: $AWS_REGION

# S3 bucket for campaign files and reviews
VITE_S3_BUCKET=$S3_BUCKET

# HTTP API Gateway base URL (upload, reviews, health endpoints)
VITE_API_URL=$API_URL

# REST API Gateway → review-campaign Lambda (agent orchestration)
# The Lambda invokes AgentCore via SDK using the ARN from SSM
VITE_AGENT_API_URL=$AGENT_API_URL
EOF

echo "✅ .env file created!"
echo ""
cat .env
echo ""
echo "🎯 Next steps:"
echo "   1. Restart your dev server: npm run dev"
echo ""
